package ecnu.testing.meethere.model;

public class Stadium {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meethere..stadium.stadium_id
     *
     * @mbg.generated Fri Dec 20 13:13:15 CST 2019
     */
    private String stadiumId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meethere..stadium.time
     *
     * @mbg.generated Fri Dec 20 13:13:15 CST 2019
     */
    private String time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meethere..stadium.price
     *
     * @mbg.generated Fri Dec 20 13:13:15 CST 2019
     */
    private Integer price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meethere..stadium.address
     *
     * @mbg.generated Fri Dec 20 13:13:15 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meethere..stadium.information
     *
     * @mbg.generated Fri Dec 20 13:13:15 CST 2019
     */
    private String information;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meethere..stadium.stadium_id
     *
     * @return the value of meethere..stadium.stadium_id
     *
     * @mbg.generated Fri Dec 20 13:13:15 CST 2019
     */
    public String getStadiumId() {
        return stadiumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meethere..stadium.stadium_id
     *
     * @param stadiumId the value for meethere..stadium.stadium_id
     *
     * @mbg.generated Fri Dec 20 13:13:15 CST 2019
     */
    public void setStadiumId(String stadiumId) {
        this.stadiumId = stadiumId == null ? null : stadiumId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meethere..stadium.time
     *
     * @return the value of meethere..stadium.time
     *
     * @mbg.generated Fri Dec 20 13:13:15 CST 2019
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meethere..stadium.time
     *
     * @param time the value for meethere..stadium.time
     *
     * @mbg.generated Fri Dec 20 13:13:15 CST 2019
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meethere..stadium.price
     *
     * @return the value of meethere..stadium.price
     *
     * @mbg.generated Fri Dec 20 13:13:15 CST 2019
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meethere..stadium.price
     *
     * @param price the value for meethere..stadium.price
     *
     * @mbg.generated Fri Dec 20 13:13:15 CST 2019
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meethere..stadium.address
     *
     * @return the value of meethere..stadium.address
     *
     * @mbg.generated Fri Dec 20 13:13:15 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meethere..stadium.address
     *
     * @param address the value for meethere..stadium.address
     *
     * @mbg.generated Fri Dec 20 13:13:15 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meethere..stadium.information
     *
     * @return the value of meethere..stadium.information
     *
     * @mbg.generated Fri Dec 20 13:13:15 CST 2019
     */
    public String getInformation() {
        return information;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meethere..stadium.information
     *
     * @param information the value for meethere..stadium.information
     *
     * @mbg.generated Fri Dec 20 13:13:15 CST 2019
     */
    public void setInformation(String information) {
        this.information = information == null ? null : information.trim();
    }

    public Stadium(String stadiumId, String time, Integer price, String address, String information) {
        this.stadiumId = stadiumId;
        this.time = time;
        this.price = price;
        this.address = address;
        this.information = information;
    }

    public Stadium(){
    }
}
