package ecnu.testing.meethere.mapper;

import ecnu.testing.meethere.model.Admin;
import ecnu.testing.meethere.model.AdminExample;
import java.util.List;

public interface AdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meethere..admin
     *
     * @mbg.generated Mon Dec 16 17:29:36 CST 2019
     */
    int deleteByPrimaryKey(Integer adminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meethere..admin
     *
     * @mbg.generated Mon Dec 16 17:29:36 CST 2019
     */
    int insert(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meethere..admin
     *
     * @mbg.generated Mon Dec 16 17:29:36 CST 2019
     */
    int insertSelective(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meethere..admin
     *
     * @mbg.generated Mon Dec 16 17:29:36 CST 2019
     */
    List<Admin> selectByExample(AdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meethere..admin
     *
     * @mbg.generated Mon Dec 16 17:29:36 CST 2019
     */
    Admin selectByPrimaryKey(Integer adminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meethere..admin
     *
     * @mbg.generated Mon Dec 16 17:29:36 CST 2019
     */
    int updateByPrimaryKeySelective(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meethere..admin
     *
     * @mbg.generated Mon Dec 16 17:29:36 CST 2019
     */
    int updateByPrimaryKey(Admin record);
}