package ecnu.testing.meethere.mapper;

import ecnu.testing.meethere.model.News;
import ecnu.testing.meethere.model.NewsExample;
import java.util.List;

public interface NewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meethere..news
     *
     * @mbg.generated Mon Dec 16 17:29:36 CST 2019
     */
    int deleteByPrimaryKey(Integer newsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meethere..news
     *
     * @mbg.generated Mon Dec 16 17:29:36 CST 2019
     */
    int insert(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meethere..news
     *
     * @mbg.generated Mon Dec 16 17:29:36 CST 2019
     */
    int insertSelective(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meethere..news
     *
     * @mbg.generated Mon Dec 16 17:29:36 CST 2019
     */
    List<News> selectByExample(NewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meethere..news
     *
     * @mbg.generated Mon Dec 16 17:29:36 CST 2019
     */
    News selectByPrimaryKey(Integer newsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meethere..news
     *
     * @mbg.generated Mon Dec 16 17:29:36 CST 2019
     */
    int updateByPrimaryKeySelective(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meethere..news
     *
     * @mbg.generated Mon Dec 16 17:29:36 CST 2019
     */
    int updateByPrimaryKey(News record);
}