package ecnu.testing.meethere.mapper;

import ecnu.testing.meethere.model.Stadium;
import ecnu.testing.meethere.model.StadiumExample;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface StadiumMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meethere..stadium
     *
     * @mbg.generated Mon Dec 16 21:18:55 CST 2019
     */
    int deleteByPrimaryKey(Integer autoIncr);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meethere..stadium
     *
     * @mbg.generated Mon Dec 16 21:18:55 CST 2019
     */
    int insert(Stadium record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meethere..stadium
     *
     * @mbg.generated Mon Dec 16 21:18:55 CST 2019
     */
    int insertSelective(Stadium record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meethere..stadium
     *
     * @mbg.generated Mon Dec 16 21:18:55 CST 2019
     */
    List<Stadium> selectByExample(StadiumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meethere..stadium
     *
     * @mbg.generated Mon Dec 16 21:18:55 CST 2019
     */
    Stadium selectByPrimaryKey(Integer autoIncr);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meethere..stadium
     *
     * @mbg.generated Mon Dec 16 21:18:55 CST 2019
     */
    int updateByPrimaryKeySelective(Stadium record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meethere..stadium
     *
     * @mbg.generated Mon Dec 16 21:18:55 CST 2019
     */
    int updateByPrimaryKey(Stadium record);
}
