package ecnu.testing.meethere.mapper;

import ecnu.testing.meethere.model.Stadium;
import ecnu.testing.meethere.model.StadiumExample;
import java.util.List;

public interface StadiumMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meethere..stadium
     *
     * @mbg.generated Fri Dec 13 20:19:57 CST 2019
     */
    int deleteByPrimaryKey(Integer autoIncr);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meethere..stadium
     *
     * @mbg.generated Fri Dec 13 20:19:57 CST 2019
     */
    int insert(Stadium record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meethere..stadium
     *
     * @mbg.generated Fri Dec 13 20:19:57 CST 2019
     */
    int insertSelective(Stadium record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meethere..stadium
     *
     * @mbg.generated Fri Dec 13 20:19:57 CST 2019
     */
    List<Stadium> selectByExample(StadiumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meethere..stadium
     *
     * @mbg.generated Fri Dec 13 20:19:57 CST 2019
     */
    Stadium selectByPrimaryKey(Integer autoIncr);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meethere..stadium
     *
     * @mbg.generated Fri Dec 13 20:19:57 CST 2019
     */
    int updateByPrimaryKeySelective(Stadium record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meethere..stadium
     *
     * @mbg.generated Fri Dec 13 20:19:57 CST 2019
     */
    int updateByPrimaryKey(Stadium record);
}