package ecnu.testing.meethere.mapper;

import ecnu.testing.meethere.model.User;
import ecnu.testing.meethere.model.UserExample;
import java.util.List;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meethere..user
     *
     * @mbg.generated Mon Dec 16 17:29:36 CST 2019
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meethere..user
     *
     * @mbg.generated Mon Dec 16 17:29:36 CST 2019
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meethere..user
     *
     * @mbg.generated Mon Dec 16 17:29:36 CST 2019
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meethere..user
     *
     * @mbg.generated Mon Dec 16 17:29:36 CST 2019
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meethere..user
     *
     * @mbg.generated Mon Dec 16 17:29:36 CST 2019
     */
    User selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meethere..user
     *
     * @mbg.generated Mon Dec 16 17:29:36 CST 2019
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meethere..user
     *
     * @mbg.generated Mon Dec 16 17:29:36 CST 2019
     */
    int updateByPrimaryKey(User record);
}