package ecnu.testing.meethere.model;

public class Admin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meethere..admin.admin_id
     *
     * @mbg.generated Mon Dec 16 17:29:36 CST 2019
     */
    private Integer adminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meethere..admin.password
     *
     * @mbg.generated Mon Dec 16 17:29:36 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meethere..admin.name
     *
     * @mbg.generated Mon Dec 16 17:29:36 CST 2019
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meethere..admin.admin_id
     *
     * @return the value of meethere..admin.admin_id
     *
     * @mbg.generated Mon Dec 16 17:29:36 CST 2019
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meethere..admin.admin_id
     *
     * @param adminId the value for meethere..admin.admin_id
     *
     * @mbg.generated Mon Dec 16 17:29:36 CST 2019
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meethere..admin.password
     *
     * @return the value of meethere..admin.password
     *
     * @mbg.generated Mon Dec 16 17:29:36 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meethere..admin.password
     *
     * @param password the value for meethere..admin.password
     *
     * @mbg.generated Mon Dec 16 17:29:36 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meethere..admin.name
     *
     * @return the value of meethere..admin.name
     *
     * @mbg.generated Mon Dec 16 17:29:36 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meethere..admin.name
     *
     * @param name the value for meethere..admin.name
     *
     * @mbg.generated Mon Dec 16 17:29:36 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}