package ecnu.testing.meethere.model;

import java.util.Date;

public class News {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meethere..news.news_id
     *
     * @mbg.generated Mon Dec 16 17:29:36 CST 2019
     */
    private Integer newsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meethere..news.title
     *
     * @mbg.generated Mon Dec 16 17:29:36 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meethere..news.content
     *
     * @mbg.generated Mon Dec 16 17:29:36 CST 2019
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meethere..news.time
     *
     * @mbg.generated Mon Dec 16 17:29:36 CST 2019
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meethere..news.name
     *
     * @mbg.generated Mon Dec 16 17:29:36 CST 2019
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meethere..news.news_id
     *
     * @return the value of meethere..news.news_id
     *
     * @mbg.generated Mon Dec 16 17:29:36 CST 2019
     */
    public Integer getNewsId() {
        return newsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meethere..news.news_id
     *
     * @param newsId the value for meethere..news.news_id
     *
     * @mbg.generated Mon Dec 16 17:29:36 CST 2019
     */
    public void setNewsId(Integer newsId) {
        this.newsId = newsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meethere..news.title
     *
     * @return the value of meethere..news.title
     *
     * @mbg.generated Mon Dec 16 17:29:36 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meethere..news.title
     *
     * @param title the value for meethere..news.title
     *
     * @mbg.generated Mon Dec 16 17:29:36 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meethere..news.content
     *
     * @return the value of meethere..news.content
     *
     * @mbg.generated Mon Dec 16 17:29:36 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meethere..news.content
     *
     * @param content the value for meethere..news.content
     *
     * @mbg.generated Mon Dec 16 17:29:36 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meethere..news.time
     *
     * @return the value of meethere..news.time
     *
     * @mbg.generated Mon Dec 16 17:29:36 CST 2019
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meethere..news.time
     *
     * @param time the value for meethere..news.time
     *
     * @mbg.generated Mon Dec 16 17:29:36 CST 2019
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meethere..news.name
     *
     * @return the value of meethere..news.name
     *
     * @mbg.generated Mon Dec 16 17:29:36 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meethere..news.name
     *
     * @param name the value for meethere..news.name
     *
     * @mbg.generated Mon Dec 16 17:29:36 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}