package ecnu.testing.meethere.model;

import java.util.Date;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meethere..order.order_id
     *
     * @mbg.generated Fri Dec 13 20:19:57 CST 2019
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meethere..order.user_id
     *
     * @mbg.generated Fri Dec 13 20:19:57 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meethere..order.stadium_id
     *
     * @mbg.generated Fri Dec 13 20:19:57 CST 2019
     */
    private Integer stadiumId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meethere..order.time
     *
     * @mbg.generated Fri Dec 13 20:19:57 CST 2019
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meethere..order.is_checked
     *
     * @mbg.generated Fri Dec 13 20:19:57 CST 2019
     */
    private Byte isChecked;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meethere..order.order_id
     *
     * @return the value of meethere..order.order_id
     *
     * @mbg.generated Fri Dec 13 20:19:57 CST 2019
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meethere..order.order_id
     *
     * @param orderId the value for meethere..order.order_id
     *
     * @mbg.generated Fri Dec 13 20:19:57 CST 2019
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meethere..order.user_id
     *
     * @return the value of meethere..order.user_id
     *
     * @mbg.generated Fri Dec 13 20:19:57 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meethere..order.user_id
     *
     * @param userId the value for meethere..order.user_id
     *
     * @mbg.generated Fri Dec 13 20:19:57 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meethere..order.stadium_id
     *
     * @return the value of meethere..order.stadium_id
     *
     * @mbg.generated Fri Dec 13 20:19:57 CST 2019
     */
    public Integer getStadiumId() {
        return stadiumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meethere..order.stadium_id
     *
     * @param stadiumId the value for meethere..order.stadium_id
     *
     * @mbg.generated Fri Dec 13 20:19:57 CST 2019
     */
    public void setStadiumId(Integer stadiumId) {
        this.stadiumId = stadiumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meethere..order.time
     *
     * @return the value of meethere..order.time
     *
     * @mbg.generated Fri Dec 13 20:19:57 CST 2019
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meethere..order.time
     *
     * @param time the value for meethere..order.time
     *
     * @mbg.generated Fri Dec 13 20:19:57 CST 2019
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meethere..order.is_checked
     *
     * @return the value of meethere..order.is_checked
     *
     * @mbg.generated Fri Dec 13 20:19:57 CST 2019
     */
    public Byte getIsChecked() {
        return isChecked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meethere..order.is_checked
     *
     * @param isChecked the value for meethere..order.is_checked
     *
     * @mbg.generated Fri Dec 13 20:19:57 CST 2019
     */
    public void setIsChecked(Byte isChecked) {
        this.isChecked = isChecked;
    }
}