package ecnu.testing.meethere.model;

import java.util.Date;

public class Stadium {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meethere..stadium.auto_incr
     *
     * @mbg.generated Fri Dec 13 20:19:57 CST 2019
     */
    private Integer autoIncr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meethere..stadium.stadium_id
     *
     * @mbg.generated Fri Dec 13 20:19:57 CST 2019
     */
    private Integer stadiumId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meethere..stadium.time
     *
     * @mbg.generated Fri Dec 13 20:19:57 CST 2019
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meethere..stadium.is_available
     *
     * @mbg.generated Fri Dec 13 20:19:57 CST 2019
     */
    private Byte isAvailable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meethere..stadium.auto_incr
     *
     * @return the value of meethere..stadium.auto_incr
     *
     * @mbg.generated Fri Dec 13 20:19:57 CST 2019
     */
    public Integer getAutoIncr() {
        return autoIncr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meethere..stadium.auto_incr
     *
     * @param autoIncr the value for meethere..stadium.auto_incr
     *
     * @mbg.generated Fri Dec 13 20:19:57 CST 2019
     */
    public void setAutoIncr(Integer autoIncr) {
        this.autoIncr = autoIncr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meethere..stadium.stadium_id
     *
     * @return the value of meethere..stadium.stadium_id
     *
     * @mbg.generated Fri Dec 13 20:19:57 CST 2019
     */
    public Integer getStadiumId() {
        return stadiumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meethere..stadium.stadium_id
     *
     * @param stadiumId the value for meethere..stadium.stadium_id
     *
     * @mbg.generated Fri Dec 13 20:19:57 CST 2019
     */
    public void setStadiumId(Integer stadiumId) {
        this.stadiumId = stadiumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meethere..stadium.time
     *
     * @return the value of meethere..stadium.time
     *
     * @mbg.generated Fri Dec 13 20:19:57 CST 2019
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meethere..stadium.time
     *
     * @param time the value for meethere..stadium.time
     *
     * @mbg.generated Fri Dec 13 20:19:57 CST 2019
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meethere..stadium.is_available
     *
     * @return the value of meethere..stadium.is_available
     *
     * @mbg.generated Fri Dec 13 20:19:57 CST 2019
     */
    public Byte getIsAvailable() {
        return isAvailable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meethere..stadium.is_available
     *
     * @param isAvailable the value for meethere..stadium.is_available
     *
     * @mbg.generated Fri Dec 13 20:19:57 CST 2019
     */
    public void setIsAvailable(Byte isAvailable) {
        this.isAvailable = isAvailable;
    }
}