package ecnu.testing.meethere.mapper;

import ecnu.testing.meethere.model.User;
import ecnu.testing.meethere.model.UserExample;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meethere..user
     *
     * @mbg.generated Thu Dec 19 18:43:21 CST 2019
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meethere..user
     *
     * @mbg.generated Thu Dec 19 18:43:21 CST 2019
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meethere..user
     *
     * @mbg.generated Thu Dec 19 18:43:21 CST 2019
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meethere..user
     *
     * @mbg.generated Thu Dec 19 18:43:21 CST 2019
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meethere..user
     *
     * @mbg.generated Thu Dec 19 18:43:21 CST 2019
     */
    User selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meethere..user
     *
     * @mbg.generated Thu Dec 19 18:43:21 CST 2019
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meethere..user
     *
     * @mbg.generated Thu Dec 19 18:43:21 CST 2019
     */
    int updateByPrimaryKey(User record);
    List<User> selectByName(String name);
    List<User> selectAllUser();
}
