// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.interactions.Actions;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class AddOrder2Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.gecko.driver","./geckodriver"); //
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void addOrder2() {
    driver.manage().window().setSize(new Dimension(1440, 900));
    driver.get("http://localhost:8081/");
    driver.findElement(By.cssSelector(".input_style:nth-child(1) > .el-input__inner")).click();
    driver.findElement(By.cssSelector(".input_style:nth-child(1) > .el-input__inner")).sendKeys("user01");
    driver.findElement(By.cssSelector(".input_style:nth-child(2) > .el-input__inner")).click();
    driver.findElement(By.cssSelector(".input_style:nth-child(2) > .el-input__inner")).sendKeys("123456");
    driver.findElement(By.cssSelector(".el-button--primary")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".el-message el-message--success"));
      assert(elements.size() == 0);
    }
    driver.findElement(By.cssSelector(".el-table__fixed-body-wrapper .el-table__row:nth-child(2) span")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".el-message el-message--success"));
      assert(elements.size() == 0);
    }
    driver.findElement(By.cssSelector(".el-date-editor--date > .el-input__inner")).click();
    driver.findElement(By.cssSelector(".available:nth-child(5) > div")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".el-button--primary"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".el-date-editor--time-select > .el-input__inner")).click();
    driver.findElement(By.cssSelector(".time-select-item:nth-child(7)")).click();
    driver.findElement(By.cssSelector(".el-button--primary > span")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".el-button--primary > span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".el-button--small:nth-child(2) > span")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".el-message el-message--success"));
      assert(elements.size() == 0);
    }
  }
}
